### ISSUE TITLE
map SVG code to the drawing board?

### ISSUE THREAD

**Issue by xiaoniaoyouhuajiang** [zhaouv/vscode-markdown-draw#1]
Sometimes there are parts of the notes that need to be changed, which requires mapping the SVG code back to the drawing board. Is this technically possible?
I think if the above features can be implemented, the usability of the plug-in will be greatly improved

**Comment by zhaouv** [comment]
The feature is `Edit/Create current line as SVG`  
If you put the cursor on the line of SVG that already exists, the SVG will reveal in the board.

**Comment by xiaoniaoyouhuajiang** [comment]
> The feature is `Edit/Create current line as SVG`
> If you put the cursor on the line of SVG that already exists, the SVG will reveal in the board.

I Got it~
Sorry to interrupt
