### ISSUE TITLE
Project still alive / Folding svg regions

### ISSUE THREAD

**Issue by femto-code** [zhaouv/vscode-markdown-draw#2]
First of all, thank you for this awesome extension - it is unique!
Is it still continued? The automatic folding of the svg elements would be a nice to have feature!

**Comment by zhaouv** [comment]
I'm waitting for the realization of this extension [Visual Studio Code Custom Folding Extension](https://github.com/maptz/Maptz.VSCode.Extensions.customfolding#feature---default-folding-preview)  
It is a preview feature `Feature - Default Folding (Preview)` in their extension.   
> Default folds define regions which will be collapsed whenever the file is opened. In the current preview version, default folds are only collapsed when the `regionfolder.collapseDefault` command is issued from the command palette.

It will be something like this
```markdown
<!-- #region drawnote --><svg .../>  
<!-- #endregion -->  
```

I have not read their source code carefully. Maybe it is easy.    

It is alive, but I am lazy. Maybe the feature in this issue will be done in months.

**Comment by femto-code** [comment]
Okay, thanks for the update. In my case this is a critical feature (collapsing long SVG areas) which would make this extension pretty useful - provided this issue is solved.
I just realized that if a SVG drawing gets loo long/big (in one line) VS Code does not allow folding this SVG area at all. This happens at the same time as the syntax highlighting stops working for this line - I guess because there is a maximal character limit per line for these functions to work.

**Comment by zhaouv** [comment]
Good catch!
seems it should be changed to things like
```markdown
<!-- #region drawnote -->
<svg .../>
<!-- #endregion -->
```
When I deal with it, it should resolve.

**Comment by femto-code** [comment]
Okay, good to hear!

**Comment by zhaouv** [comment]
done
