### ISSUE TITLE
Erase function not working with tablet 

### ISSUE THREAD

**Issue by pranav083** [zhaouv/vscode-markdown-draw#6]
Thanks for this extension. it is relatively easier to work with.
Device name: X-pen Graphical tablet Deco 01 (V2)  

As the eraser function is working fine when using a mouse but the same process does not work if I try to use the stylus of the tablet to invoke the erase function it is not working.
Please look into the issue. 
Thanks for the extension.

**Comment by zhaouv** [comment]
It works for my Surface Pen, I have no idea how to fix it for other devices without extra information. 
You can clone the repo, and change the line 139 to `console.log(e)` for file *board/main.js* and double click *webview.html*. While using the easier after press F12, you will see logs like this.
<img width="366" alt="image" src="https://user-images.githubusercontent.com/26158289/200311013-bbcb1d7d-fd38-4a4e-8116-7f39e0862c17.png">
click the triangle, copy the content to me (or snap as picture). may figure out how to fix it. For example, when the key `buttons` become to 32, I know the eraser of Surface Pen is using. (so you may better also save the content of normal drawing of your device)

demo:
```
isTrusted
: 
true
altKey
: 
false
altitudeAngle
: 
1.5707963267948966
azimuthAngle
: 
0
bubbles
: 
true
button
: 
5
buttons
: 
32
cancelBubble
: 
false
cancelable
: 
true
clientX
: 
391.4666748046875
clientY
: 
186.40000915527344
composed
: 
true
ctrlKey
: 
false
currentTarget
: 
null
defaultPrevented
: 
false
detail
: 
0
eventPhase
: 
0
fromElement
: 
null
height
: 
0.8000000715255737
isPrimary
: 
true
layerX
: 
95
layerY
: 
186
metaKey
: 
false
movementX
: 
0
movementY
: 
0
offsetX
: 
387.0041809082031
offsetY
: 
133.9000244140625
pageX
: 
391.4666748046875
pageY
: 
186.40000915527344
path
: 
(8) [svg#svg, div.svg-container, div.container, div, body, html, document, Window]
pointerId
: 
3
pointerType
: 
"pen"
pressure
: 
0.4658203125
relatedTarget
: 
null
returnValue
: 
true
screenX
: 
489.3333435058594
screenY
: 
304
shiftKey
: 
false
sourceCapabilities
: 
null
srcElement
: 
svg#svg
tangentialPressure
: 
0
target
: 
svg#svg
tiltX
: 
0
tiltY
: 
0
timeStamp
: 
391700.7000000002
toElement
: 
null
twist
: 
0
type
: 
"pointerdown"
view
: 
Window {window: Window, self: Window, document: document, name: '', location: Location, …}
which
: 
6
width
: 
0.8000000715255737
x
: 
391.4666748046875
y
: 
186.40000915527344
```
